package org.earthChem.dal.hibernate.bean;
// Generated Oct 1, 2013 9:35:38 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.util.Date;


/**
 * Reference generated by hbm2java
 */

public class ReferenceHbm  implements java.io.Serializable {

    // Fields    

     private BigDecimal refNum;
     private String title;
     private String journal;
     private String volume;
     private String issue;
     private BigDecimal firstPage;
     private BigDecimal lastPage;
     private BigDecimal pubYear;
     private String bookTitle;
     private String bookEditor;
     private String publisher;
     private String dataEntered;
     private Date dataEnteredDate;
     private String publicationDoi;
     private String status;
     private String publicComment;
     private String internalComment;


    // Constructors

    /** default constructor */
    public ReferenceHbm() {
    }

	/** minimal constructor */
    public ReferenceHbm(BigDecimal refNum) {
        this.refNum = refNum;
    }
    
    /** full constructor */
    public ReferenceHbm(BigDecimal refNum, String title, String journal, String volume, String issue, BigDecimal firstPage, BigDecimal lastPage, BigDecimal pubYear, String bookTitle, String bookEditor, String publisher, String dataEntered, Date dataEnteredDate, String publicationDoi, String status, String publicComment, String internalComment) {
        this.refNum = refNum;
        this.title = title;
        this.journal = journal;
        this.volume = volume;
        this.issue = issue;
        this.firstPage = firstPage;
        this.lastPage = lastPage;
        this.pubYear = pubYear;
        this.bookTitle = bookTitle;
        this.bookEditor = bookEditor;
        this.publisher = publisher;
        this.dataEntered = dataEntered;
        this.dataEnteredDate = dataEnteredDate;
        this.publicationDoi = publicationDoi;
        this.status = status;
        this.publicComment = publicComment;
        this.internalComment = internalComment;
    }
    

   
    // Property accessors

    public BigDecimal getRefNum() {
        return this.refNum;
    }
    
    public void setRefNum(BigDecimal refNum) {
        this.refNum = refNum;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public String getJournal() {
        return this.journal;
    }
    
    public void setJournal(String journal) {
        this.journal = journal;
    }

    public String getVolume() {
        return this.volume;
    }
    
    public void setVolume(String volume) {
        this.volume = volume;
    }

    public String getIssue() {
        return this.issue;
    }
    
    public void setIssue(String issue) {
        this.issue = issue;
    }

    public BigDecimal getFirstPage() {
        return this.firstPage;
    }
    
    public void setFirstPage(BigDecimal firstPage) {
        this.firstPage = firstPage;
    }

    public BigDecimal getLastPage() {
        return this.lastPage;
    }
    
    public void setLastPage(BigDecimal lastPage) {
        this.lastPage = lastPage;
    }

    public BigDecimal getPubYear() {
        return this.pubYear;
    }
    
    public void setPubYear(BigDecimal pubYear) {
        this.pubYear = pubYear;
    }

    public String getBookTitle() {
        return this.bookTitle;
    }
    
    public void setBookTitle(String bookTitle) {
        this.bookTitle = bookTitle;
    }

    public String getBookEditor() {
        return this.bookEditor;
    }
    
    public void setBookEditor(String bookEditor) {
        this.bookEditor = bookEditor;
    }

    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public String getDataEntered() {
        return this.dataEntered;
    }
    
    public void setDataEntered(String dataEntered) {
        this.dataEntered = dataEntered;
    }

    public Date getDataEnteredDate() {
        return this.dataEnteredDate;
    }
    
    public void setDataEnteredDate(Date dataEnteredDate) {
        this.dataEnteredDate = dataEnteredDate;
    }

    public String getPublicationDoi() {
        return this.publicationDoi;
    }
    
    public void setPublicationDoi(String publicationDoi) {
        this.publicationDoi = publicationDoi;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getPublicComment() {
        return this.publicComment;
    }
    
    public void setPublicComment(String publicComment) {
        this.publicComment = publicComment;
    }

    public String getInternalComment() {
        return this.internalComment;
    }
    
    public void setInternalComment(String internalComment) {
        this.internalComment = internalComment;
    }
   








}
